"""
instance.py
===========
Builds an SB-PHEP-II instance from the authenticated data files.

Design notes
------------
* Every physical, monetary and emissions parameter comes from ``data/`` and
  carries provenance (see ``data_io``).  Quantities that are *not* publicly
  observable at the level the model needs (the split of a corridor's container
  volume between individual carriers, and the day-to-day dispersion of demand)
  are generated by an explicit, seeded, documented rule; the rule's parameters
  are exposed here and are varied in the sensitivity analysis.
* The leader's instruments are *discrete by construction*: an arc is either
  chargeable or not; charging capacity is procured in whole 350 kW bays; and
  corridor charges are set on a regulated menu of levels.  This is how such
  instruments are actually deployed, and it is what makes the exact
  strong-duality reformulation in ``models.py`` finite and tight.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field, replace
from typing import Dict, List, Tuple

import numpy as np

from . import data_io as D

Arc = Tuple[str, str]
Edge = Tuple[str, str]


# --------------------------------------------------------------------------- #
#  scenario tree                                                               #
# --------------------------------------------------------------------------- #
#  Grid states are named after the emission factor they use.  "clean" is a
#  renewable-rich hour, "average" the published national annual average, and
#  "marginal" the fossil unit that actually responds to incremental load (for
#  India this is the CEA operating margin, an authenticated published figure).
#
#  The price and headroom multipliers below are *shape* parameters: the relative
#  spread between the states.  Their levels are not used directly.  The state
#  probabilities and the price multipliers are rescaled in :func:`_grid_tree` so
#  that the resulting distribution reproduces the one quantity each country
#  actually publishes -- its annual average grid emission factor -- and so that
#  the expected electricity price equals the published national price.  A tree
#  whose mean is not the published mean would make every cross-country statement
#  a statement about the construction rather than about the country.
GRID_STATES = {
    #  name        ef key        price shape   charging headroom multiplier
    "clean":    ("ef_clean",    0.80, 1.00),
    "average":  ("ef_avg",      1.00, 0.80),
    "marginal": ("ef_marginal", 1.55, 0.45),
}
DEMAND_LEVELS = {"L": 0.80, "M": 1.00, "H": 1.30}

#  Probability mass placed on the two outer grid states together.  The remainder
#  goes on the published average.  Within the outer pair the split is *solved*, so
#  that the mean of the whole distribution is the published average.
OUTER_MASS = 0.50

#  ------------------------------------------------------------------------- #
#  Structural constants of the instance generator.
#
#  These are modelling choices, not measurements.  They are named here rather than
#  left as literals in the middle of the code, and recorded in the instance
#  metadata, so that the claim that every input has a row in data/DATA_SOURCES.md
#  holds of them too; that file carries a row for each.
#  ------------------------------------------------------------------------- #
OPERATING_DAYS = 250.0        # working days per year the corridor is modelled over
HEADROOM_FRACTION = 0.75      # clean-state charging headroom, as a fraction of the
                              # energy full electrification at mean demand would need
ARC_CAP_MULTIPLE = 4.0        # arc truck-movement capacity, as a multiple of peak boxes
SHARE_DIRICHLET = 6.0         # Dirichlet concentration for the carrier size split
TILT_DIRICHLET = 8.0          # concentration at zero heterogeneity for the node tilt
PROCUREMENT_STEPS = 2 ** 7 - 1  # charging procurement steps spanned per corridor
DEMAND_PROBS = {"L": 0.30, "M": 0.40, "H": 0.30}   # demand-level probabilities


def _grid_tree(reg: Dict[str, float], grid_states) -> Tuple[Dict[str, float],
                                                            Dict[str, float]]:
    """State probabilities and price multipliers that preserve published means.

    Returns ``(prob, price_multiplier)`` over ``grid_states``.

    With all three states present, let ``ef_c <= ef_a <= ef_m`` be the clean,
    published-average and marginal factors, and put mass ``w`` on the outer pair.
    Solving

        p_c + p_m = w,      p_c ef_c + p_m ef_m = w ef_a

    gives ``p_c = w (ef_a - ef_m) / (ef_c - ef_m)``, which lies in ``[0, w]``
    because ``ef_a`` lies between the two, and makes the expected emission factor
    exactly ``ef_a`` -- the published number.  The price multipliers are then
    scaled by a single factor so that the expected electricity price is the
    published national price, keeping their relative spread as given above.

    With a subset of the states the mean cannot be matched in general, so the
    probabilities fall back to an equal split and the multipliers are still
    normalised to preserve the expected price.  That case is used only in the
    scalability study, where the economics are not being reported.
    """
    keys = list(grid_states)
    ef = {g: reg[GRID_STATES[g][0]] for g in keys}
    shape = {g: GRID_STATES[g][1] for g in keys}

    if set(keys) == set(GRID_STATES):
        efc, efa, efm = ef["clean"], ef["average"], ef["marginal"]
        if abs(efc - efm) < 1e-12:
            p = {g: 1.0 / 3.0 for g in keys}
        else:
            pc = OUTER_MASS * (efa - efm) / (efc - efm)
            pc = min(max(pc, 0.0), OUTER_MASS)
            p = {"clean": pc, "marginal": OUTER_MASS - pc,
                 "average": 1.0 - OUTER_MASS}
    else:
        p = {g: 1.0 / len(keys) for g in keys}

    #  scale the price shape so that E[multiplier] = 1, i.e. the expected price is
    #  the published national price rather than 15% above it
    mean_shape = sum(p[g] * shape[g] for g in keys)
    k = 1.0 / mean_shape if mean_shape > 1e-12 else 1.0
    mult = {g: shape[g] * k for g in keys}
    return p, mult


@dataclass
class Instance:
    """A complete SB-PHEP-II instance."""

    name: str
    country: str
    port: str

    # ---- network ----
    nodes: List[str]
    o: str
    Dn: List[str]                       # demand nodes
    arcs: List[Arc]
    edges: List[Edge]
    E: List[Edge]                       # electrifiable edges (leader's design space)
    dist: Dict[Arc, float]              # km
    edge_of_arc: Dict[Arc, Edge]
    arcs_of_edge: Dict[Edge, List[Arc]]
    node_info: Dict[str, dict]

    # ---- agents & uncertainty ----
    C: List[str]
    S: List[str]
    prob: Dict[str, float]
    DI: Dict[Tuple[str, str, str], float]   # (carrier, node, scenario) import loads
    DE: Dict[Tuple[str, str, str], float]   # (carrier, node, scenario) export loads

    # ---- energy regime ----
    price: Dict[str, float]             # USD/kWh, electricity, per scenario
    ef: Dict[str, float]                # kgCO2/kWh, grid, per scenario
    Gavail: Dict[str, float]            # kWh/day system charging headroom
    p_diesel: float                     # USD/L
    f_diesel: float                     # L/km
    e_elec: float                       # kWh/km drawn from the charger (grid side)
    e_battery: float                    # kWh/km at the battery (as measured)
    charger_eff: float                  # grid-to-battery charging efficiency
    psave: float                        # platooning traction-energy saving (fraction)
    rho: float                          # largest platoonable share of an arc's trucks
    ef_diesel: float                    # kgCO2/L

    # ---- operating economics ----
    wage: float                         # USD/truck-km
    c_plat: float                       # USD per platooned truck per arc
    PEN: float                          # USD per undelivered container
    w_emis: float                       # USD/kgCO2 (social cost of carbon)
    w_grid: float                       # USD/kWh (grid-stress externality)
    H: float                            # operating days per year

    # ---- leader design space (all discrete) ----
    K_fix: Dict[Edge, float]            # USD/yr fixed electrification cost
    K_km: Dict[Edge, float]             # USD/yr per km
    module_kwh: float                   # kWh/day per charging bay
    module_cost: float                  # USD/yr per bay
    n_bits: int                         # binary expansion bits for bays per edge
    theta_menu: List[float]             # USD per truck-km, corridor charge levels
    sigma_menu: List[float]             # USD per kWh, charging surcharge levels

    # ---- bounds ----
    Cap: Dict[Arc, float]               # truck movements per day on an arc

    #  Share of the corridor's *shared physical resources* (arc capacity,
    #  installed charging capacity, grid headroom) that this instance is
    #  entitled to.  It is 1 for the grand coalition and the coalition's share
    #  of loaded container-kilometres for a sub-coalition, which is what makes
    #  the cooperative cost game subadditive by construction: the sum of the
    #  members' stand-alone solutions is always feasible for the coalition.
    resource_share: float = 1.0

    # ---- provenance ----
    meta: dict = field(default_factory=dict)

    # -- convenience -------------------------------------------------------- #
    @property
    def n_bays_max(self) -> int:
        return 2 ** self.n_bits - 1

    def g_max(self) -> float:
        return self.n_bays_max * self.module_kwh

    def out_arcs(self, n: str) -> List[Arc]:
        return [a for a in self.arcs if a[0] == n]

    def in_arcs(self, n: str) -> List[Arc]:
        return [a for a in self.arcs if a[1] == n]

    def elec_arcs(self) -> List[Arc]:
        return [a for a in self.arcs if self.edge_of_arc[a] in self.E]

    def size(self) -> dict:
        return {"nodes": len(self.nodes), "arcs": len(self.arcs), "edges": len(self.edges),
                "electrifiable": len(self.E), "carriers": len(self.C),
                "scenarios": len(self.S),
                "design_space": (2 ** len(self.E)) * ((self.n_bays_max + 1) ** len(self.E))
                                * (len(self.theta_menu) ** len(self.E))
                                * (len(self.sigma_menu) ** len(self.S))}


# --------------------------------------------------------------------------- #
#  builder                                                                     #
# --------------------------------------------------------------------------- #
def build_instance(network: str = "vizag",
                   n_carriers: int = 3,
                   demand_levels: Tuple[str, ...] = ("L", "H"),
                   grid_states: Tuple[str, ...] = ("clean", "average", "marginal"),
                   seed: int = 20260909,
                   heterogeneity: float = 0.55,
                   demand_scale: float = 1.0,
                   n_bits: int | None = None,
                   n_theta: int = 9,
                   n_sigma: int = 9,
                   theta_max: float = 0.30,
                   sigma_max: float = 0.30,
                   scc: float | None = None,
                   country: str | None = None,
                   grid_country: str | None = None) -> Instance:
    """Assemble an instance.

    ``n_bits`` controls how many charging bays may be installed on one edge
    (``2**n_bits - 1``).  Leave it ``None`` to have it derived from the corridor's
    grid headroom, which is what keeps the cross-corridor comparison honest.

    ``heterogeneity`` in [0,1] controls how differently the carriers'
    destination portfolios are tilted; 0 makes the carriers identical (and the
    horizontal-collaboration game degenerate), 1 makes each carrier's volume
    concentrate on a distinct subset of nodes.
    """
    pars = D.load_parameters()
    ports = D.load_ports()
    regimes = D.load_energy_regimes()

    if network not in ports:
        raise KeyError(f"unknown network {network!r}; have {sorted(ports)}")
    pinfo = ports[network]
    ctry = country or pinfo["country"]
    if ctry not in regimes:
        raise KeyError(f"unknown country {ctry!r}; have {sorted(regimes)}")
    reg = dict(regimes[ctry])

    #  ``country`` swaps the whole national regime: grid carbon, electricity price,
    #  diesel price and the non-fuel haulage cost.  That is the right object for a
    #  question about transplanting a corridor to another country, but it is the
    #  wrong one for a question about the *grid*, because the haulage cost alone
    #  ranges more than threefold across these four countries and is not a property
    #  of any power system.  ``grid_country`` therefore swaps only the three
    #  emission factors, holding every price and cost at ``country``'s values, so
    #  that the matrix has a clean grid-only dimension as well as a regime one.
    if grid_country is not None:
        if grid_country not in regimes:
            raise KeyError(f"unknown grid country {grid_country!r}")
        gsrc = regimes[grid_country]
        for k in ("ef_clean", "ef_avg", "ef_marginal"):
            reg[k] = gsrc[k]
        reg["ef_source"] = (f"grid factors from {grid_country}; prices and haulage "
                            f"cost from {ctry}: " + gsrc["ef_source"])

    net = D.load_network(network, pinfo["circuity"])
    rng = np.random.default_rng(seed)

    H = OPERATING_DAYS

    # ------------------------------------------------------------------ #
    # 1. corridor road volume from published throughput                   #
    # ------------------------------------------------------------------ #
    #   Transshipment boxes never touch a road, so the road share is applied to
    #   hinterland throughput only:
    #      road containers = TEU x (1 - transshipment) x road share / (TEU per truck)
    daily_boxes = (pinfo["teu"] * (1.0 - pinfo["transshipment_share"])
                   * pinfo["road_share"] / pinfo["truck_teu_factor"] / H)
    daily_boxes *= demand_scale

    weights = {n: net.node_info[n]["demand_weight"] for n in net.demand_nodes}
    wsum = sum(weights.values())
    if wsum <= 0:
        raise ValueError(f"network {network}: demand weights sum to zero")
    weights = {n: w / wsum for n, w in weights.items()}

    node_vol = {n: daily_boxes * weights[n] for n in net.demand_nodes}
    node_imp = {n: node_vol[n] * (1.0 - net.node_info[n]["exp_share"]) for n in net.demand_nodes}
    node_exp = {n: node_vol[n] * net.node_info[n]["exp_share"] for n in net.demand_nodes}

    # ------------------------------------------------------------------ #
    # 2. carriers: market shares and destination tilts                    #
    # ------------------------------------------------------------------ #
    C = [f"c{i + 1}" for i in range(n_carriers)]
    shares = rng.dirichlet(np.full(n_carriers, SHARE_DIRICHLET))   # size dispersion
    conc = max(0.25, TILT_DIRICHLET * (1.0 - heterogeneity))   # low conc = strong tilt
    tilt = {}
    for n in net.demand_nodes:
        tilt[n] = rng.dirichlet(np.full(n_carriers, conc))

    # ------------------------------------------------------------------ #
    # 3. scenario tree                                                    #
    # ------------------------------------------------------------------ #
    for gs in grid_states:
        if gs not in GRID_STATES:
            raise KeyError(f"unknown grid state {gs!r}")
    for dl in demand_levels:
        if dl not in DEMAND_LEVELS:
            raise KeyError(f"unknown demand level {dl!r}")

    S, prob, price, ef, Gav = [], {}, {}, {}, {}
    # demand-level probabilities (triangular-ish) and grid-state probabilities
    dl_p = _normalise(DEMAND_PROBS, demand_levels)
    gs_p, gs_mult = _grid_tree(reg, grid_states)

    for dl in demand_levels:
        for gs in grid_states:
            s = f"{dl}-{gs[:2].upper()}"
            S.append(s)
            prob[s] = dl_p[dl] * gs_p[gs]
            price[s] = round(reg["elec_price"] * gs_mult[gs], 5)
            ef[s] = reg[GRID_STATES[gs][0]]

    # demand realisations
    DI, DE = {}, {}
    for c_i, c in enumerate(C):
        for n in net.demand_nodes:
            frac = shares[c_i] * tilt[n][c_i]
            denom = float(sum(shares[k] * tilt[n][k] for k in range(n_carriers)))
            frac = frac / denom if denom > 0 else 1.0 / n_carriers
            for s in S:
                dl = s.split("-")[0]
                mult = DEMAND_LEVELS[dl]
                DI[(c, n, s)] = round(node_imp[n] * frac * mult, 3)
                DE[(c, n, s)] = round(node_exp[n] * frac * mult, 3)

    # ------------------------------------------------------------------ #
    # 4. technical & economic parameters                                  #
    # ------------------------------------------------------------------ #
    #  The published consumption figure is measured at the vehicle and excludes
    #  charging losses.  Everything downstream of here -- the charging-capacity
    #  rows, the emission accounting, the per-kWh surcharge and the grid-stress
    #  term -- is about energy *drawn from the corridor's chargers*, so the model's
    #  epsilon is the battery figure grossed up by the charging efficiency.
    e_battery = pars["e_elec"]["value"]
    charger_eff = pars["charger_efficiency"]["value"]
    e_elec = e_battery / charger_eff
    f_dies = pars["f_diesel"]["value"]
    psave = pars["platoon_saving"]["value"]
    rho = pars["platoon_share_cap"]["value"]
    ef_dies = pars["ef_diesel_ttw"]["value"]
    scc_v = pars["scc"]["value"] if scc is None else scc
    w_grid = pars["grid_stress_weight"]["value"]
    PEN = pars["unmet_penalty"]["value"]
    c_plat = pars["c_platoon"]["value"]

    #  Road-haulage operating cost per truck-kilometre excluding fuel, taken
    #  from the country's own row in data/energy_regimes.csv.
    wage = reg["wage"]

    # ------------------------------------------------------------------ #
    # 5. charging headroom, capacities, capital costs                     #
    # ------------------------------------------------------------------ #
    #  Full-electrification energy requirement at mean demand, used as the
    #  reference against which grid headroom is expressed.
    mean_mult = float(np.mean([DEMAND_LEVELS[dl] for dl in demand_levels]))
    total_box_km = 0.0
    for n in net.demand_nodes:
        # shortest-path km from the port, used only for scaling constants
        total_box_km += node_vol[n] * _sp_km(net, net.port_node, n)
    ref_energy = total_box_km * mean_mult * e_elec * 2.0   # out and back

    Gav = {}
    for s in S:
        gs = [g for g in grid_states if g[:2].upper() == s.split("-")[1]][0]
        _, _, gmul = GRID_STATES[gs]
        Gav[s] = round(HEADROOM_FRACTION * ref_energy * gmul, 1)

    peak_boxes = daily_boxes * max(DEMAND_LEVELS[dl] for dl in demand_levels)
    Cap = {a: round(ARC_CAP_MULTIPLE * peak_boxes, 1) for a in net.arcs}

    #  How many charging bays may the leader put on one edge?  A fixed bit width
    #  would silently cap the design: three bits allow at most seven bays, which
    #  is ample on a corridor carrying a thousand containers a day and absurdly
    #  small on one carrying ten thousand, so the cross-corridor comparison would
    #  be measuring the encoding rather than the economics.  The bound is
    #  therefore derived: installing more capacity system-wide than the largest
    #  scenario's grid headroom is useless (the valid inequality in models.py says
    #  so), and that headroom divided by the bay size is the natural ceiling.
    #  Capacity is procured in whole units, and the unit is a *hub* rather than a
    #  single bay.  One 350 kW bay is the right unit on a corridor moving a
    #  thousand containers a day; a gateway moving ten thousand does not buy
    #  chargers one bay at a time, and pretending it does would make the model
    #  size -- and hence what the cross-corridor comparison is measuring -- depend
    #  on the corridor's volume.  The hub is therefore sized so that the same
    #  number of procurement steps (127) spans each corridor's grid headroom, and
    #  the step size is reported in the instance metadata.
    bay_kwh = pars["charger_module_kwh"]["value"]
    bay_cost = pars["charger_capex"]["value"]
    steps = PROCUREMENT_STEPS
    bays_per_hub = max(1, math.ceil(max(Gav.values()) / (bay_kwh * steps)))
    module_kwh = bay_kwh * bays_per_hub
    module_cost = bay_cost * bays_per_hub
    if n_bits is None:
        n_bits = int(min(12, max(3, math.ceil(
            math.log2(max(Gav.values()) / module_kwh + 1.0)))))

    K_fix = {e: pars["electrify_capex_fixed"]["value"] for e in net.electrifiable}
    K_km = {e: pars["electrify_capex_km"]["value"] for e in net.electrifiable}

    arcs_of_edge: Dict[Edge, List[Arc]] = {e: [] for e in net.edges}
    for a in net.arcs:
        arcs_of_edge[net.edge_of_arc[a]].append(a)

    #  The tariff menus are a uniform grid *augmented with the closed-form
    #  Pigouvian levels of Theorem 2*, so that the finite-menu reformulation can
    #  attain the first best exactly rather than approximately.  Regulators set
    #  charges on a published schedule, so a finite menu is also the realistic
    #  description of the instrument.
    theta_star = scc_v * ef_dies * f_dies
    sigma_star = sorted({round(scc_v * ef[s] + w_grid, 6) for s in S})
    theta_menu = sorted(_menu(theta_max, n_theta) | {round(theta_star, 6)})
    sigma_menu = sorted(_menu(sigma_max, n_sigma) | set(sigma_star))

    meta = {
        "network_source": pinfo["source"],
        "circuity": pinfo["circuity"],
        "circuity_check": pinfo["circuity_check"],
        "energy_source": reg["ef_source"],
        "price_source": reg["price_source"],
        "diesel_source": reg["diesel_source"],
        "accessed": reg["accessed"],
        "daily_boxes": round(daily_boxes, 2),
        "teu": pinfo["teu"], "teu_year": pinfo["teu_year"],
        "road_share": pinfo["road_share"],
        "transshipment_share": pinfo["transshipment_share"],
        "bays_per_hub": bays_per_hub, "hub_kwh": module_kwh, "hub_cost": module_cost,
        "seed": seed, "heterogeneity": heterogeneity,
        "carrier_shares": [round(float(x), 4) for x in shares],
        #  diagnostics a reader should be able to check without rerunning anything:
        #  the tree's expected grid factor and electricity price against the two
        #  published numbers it is calibrated to reproduce, and the grid-side
        #  consumption against the battery-side figure it is derived from.
        "grid_state_probabilities": {g: round(gs_p[g], 4) for g in grid_states},
        "grid_price_multipliers": {g: round(gs_mult[g], 4) for g in grid_states},
        "expected_ef_kgco2_per_kwh": round(
            sum(prob[s] * ef[s] for s in S), 5),
        "published_ef_avg": reg["ef_avg"],
        "expected_elec_price_usd_kwh": round(
            sum(prob[s] * price[s] for s in S), 5),
        "published_elec_price": reg["elec_price"],
        "e_battery_kwh_per_km": e_battery,
        "charger_efficiency": charger_eff,
        "e_grid_kwh_per_km": round(e_elec, 4),
        #  the two numbers a corridor authority would actually publish
        "theta_star_usd_per_truck_km": round(theta_star, 5),
        "sigma_star_usd_per_kwh": {g: round(scc_v * reg[GRID_STATES[g][0]] + w_grid, 5)
                                   for g in grid_states},
        "sigma_star_as_pct_of_elec_price": {
            g: round(100.0 * (scc_v * reg[GRID_STATES[g][0]] + w_grid)
                     / max(reg["elec_price"] * gs_mult[g], 1e-9), 1)
            for g in grid_states},
        "headroom_fraction_of_full_electrification": HEADROOM_FRACTION,
        "arc_capacity_multiple_of_peak_boxes": ARC_CAP_MULTIPLE,
        "operating_days_per_year": H,
    }

    return Instance(
        name=network, country=ctry, port=pinfo["port"],
        nodes=net.nodes, o=net.port_node, Dn=net.demand_nodes,
        arcs=net.arcs, edges=net.edges, E=net.electrifiable,
        dist=net.dist, edge_of_arc=net.edge_of_arc, arcs_of_edge=arcs_of_edge,
        node_info=net.node_info,
        C=C, S=S, prob=prob, DI=DI, DE=DE,
        price=price, ef=ef, Gavail=Gav,
        p_diesel=reg["diesel_price"], f_diesel=f_dies, e_elec=e_elec,
        e_battery=e_battery, charger_eff=charger_eff,
        psave=psave, rho=rho, ef_diesel=ef_dies,
        wage=wage, c_plat=c_plat, PEN=PEN, w_emis=scc_v, w_grid=w_grid, H=H,
        K_fix=K_fix, K_km=K_km,
        module_kwh=module_kwh, module_cost=module_cost,
        n_bits=n_bits, theta_menu=theta_menu, sigma_menu=sigma_menu,
        Cap=Cap, meta=meta,
    )


def _menu(top: float, n: int) -> set:
    """A charge menu: a fine uniform grid where the optimum lies, then a coarse
    geometric extension so that the range is never the binding constraint.

    A regulator publishes a schedule of levels rather than a continuous price,
    so a finite menu is the faithful description of the instrument; making the
    upper end generous is what lets the paper claim that a family's failure to
    reach an emission target is structural rather than an artefact of the grid.
    """
    fine = {round(top * k / (n - 1), 6) for k in range(n)}
    coarse = {round(top * m, 6) for m in (1.5, 2.0, 3.0, 5.0)}
    return fine | coarse


def _normalise(base: Dict[str, float], keys) -> Dict[str, float]:
    sub = {k: base[k] for k in keys}
    tot = sum(sub.values())
    return {k: v / tot for k, v in sub.items()}


def _sp_km(net, src: str, dst: str) -> float:
    """Dijkstra shortest path length in km (used only for scaling constants)."""
    import heapq
    d = {n: math.inf for n in net.nodes}
    d[src] = 0.0
    pq = [(0.0, src)]
    while pq:
        du, u = heapq.heappop(pq)
        if du > d[u] + 1e-12:
            continue
        if u == dst:
            return du
        for a in net.arcs:
            if a[0] != u:
                continue
            v = a[1]
            nd = du + net.dist[a]
            if nd < d[v] - 1e-12:
                d[v] = nd
                heapq.heappush(pq, (nd, v))
    return d[dst]


ALLOCATION_RULES = ("box_km", "box_count", "equal")


def sub_instance(inst: Instance, coalition, rule: str = "box_km") -> Instance:
    """Restrict an instance to a sub-coalition of carriers.

    The shared grid headroom and the arc capacities are public resources
    provisioned by the corridor authority, and a sub-coalition is entitled only to
    the share of them that its own traffic would justify.  Giving every coalition
    the whole corridor's capacity is not a neutral choice: it makes the
    characteristic function non-subadditive, and the resulting "collaboration
    gain" can come out negative -- a property of the construction rather than of
    collaboration.

    Three entitlement rules are available, because the choice is an assumption and
    the reader is entitled to see how much rides on it:

    ``box_km``     (default) share of expected *loaded container-kilometres*, the
                   physically meaningful driver of charging demand;
    ``box_count``  share of container moves, which is what earlier work uses and
                   which biases the game when carriers' distance profiles differ;
    ``equal``      an equal split among carriers, the most naive rule.
    """
    K = list(coalition)
    if not K:
        raise ValueError("empty coalition")
    if rule not in ALLOCATION_RULES:
        raise ValueError(f"unknown allocation rule {rule!r}")
    Kset = set(K)
    sp = shortest_path_km(inst)

    def weight(cs):
        tot = 0.0
        for (c, n, s) in inst.DI:
            if c in cs:
                boxes = inst.DI[(c, n, s)] + inst.DE[(c, n, s)]
                tot += inst.prob[s] * boxes * (sp[n] if rule == "box_km" else 1.0)
        return tot

    if rule == "equal":
        frac = len(K) / len(inst.C)
    else:
        denom = weight(set(inst.C))
        frac = weight(Kset) / denom if denom > 0 else len(K) / len(inst.C)
    DI = {k: v for k, v in inst.DI.items() if k[0] in Kset}
    DE = {k: v for k, v in inst.DE.items() if k[0] in Kset}
    Gav = {s: inst.Gavail[s] * frac for s in inst.S}
    Cap = {a: inst.Cap[a] * frac for a in inst.arcs}
    return replace(inst, C=K, DI=DI, DE=DE, Gavail=Gav, Cap=Cap,
                   resource_share=inst.resource_share * frac)


def shortest_path_km(inst: Instance) -> Dict[str, float]:
    """Road distance from the port to every node (used only for scaling rules)."""
    import heapq
    d = {x: math.inf for x in inst.nodes}
    d[inst.o] = 0.0
    adj: Dict[str, List[Arc]] = {x: [] for x in inst.nodes}
    for a in inst.arcs:
        adj[a[0]].append(a)
    pq = [(0.0, inst.o)]
    while pq:
        du, u = heapq.heappop(pq)
        if du > d[u] + 1e-12:
            continue
        for a in adj[u]:
            nd = du + inst.dist[a]
            if nd < d[a[1]] - 1e-12:
                d[a[1]] = nd
                heapq.heappush(pq, (nd, a[1]))
    return d


if __name__ == "__main__":  # pragma: no cover
    for nm in D.available_networks():
        inst = build_instance(nm)
        sz = inst.size()
        print(f"{nm:12s} {inst.port:22s} {inst.country:12s} "
              f"boxes/day={inst.meta['daily_boxes']:8.1f} "
              f"arcs={sz['arcs']:3d} E={sz['electrifiable']:2d} "
              f"S={sz['scenarios']} design_space=1e{math.log10(sz['design_space']):.0f}")
        print("     price/scen:", inst.price, " ef:", inst.ef)
        print("     Gavail:", {k: round(v) for k, v in inst.Gavail.items()})
