#!/usr/bin/env python3
"""
make_interpretation.py
======================
Write ``outputs/RESULTS_INTERPRETATION.md`` from the result files.

The note is generated rather than written by hand for the same reason the
manuscript's numbers are: a hand-written interpretation of a computational study
goes stale the first time the study is re-run, and a stale interpretation is
worse than none. Every figure below is read from ``outputs/tables/*.csv`` or
``outputs/summary.json`` at the moment of writing, and every sentence that could
come out either way is branched on the actual value.
"""
from __future__ import annotations

import csv
import json
import math
import os
import sys
from typing import List

ROOT = os.path.dirname(os.path.abspath(__file__))
TAB = os.path.join(ROOT, "outputs", "tables")
OUT = os.path.join(ROOT, "outputs", "RESULTS_INTERPRETATION.md")


def read(name: str) -> List[dict]:
    p = os.path.join(TAB, name)
    if not os.path.exists(p):
        return []
    with open(p, newline="") as fh:
        return list(csv.DictReader(fh))


def f(v, d=math.nan) -> float:
    try:
        return float(v)
    except (TypeError, ValueError):
        return d


def m(x, digits=0) -> str:
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "n/a"
    return f"{x:,.{digits}f}"


def main() -> None:
    sys.path.insert(0, ROOT)
    from src import data_io as D
    pars, reg = D.load_parameters(), D.load_energy_regimes()

    sp = os.path.join(ROOT, "outputs", "summary.json")
    S = json.load(open(sp)) if os.path.exists(sp) else {}
    L: List[str] = []
    w = L.append

    w("# SB-PHEP-II — what the results say")
    w("")
    w("Generated by `make_interpretation.py` from the files in `outputs/`. "
      "Re-running the study rewrites this note, so it cannot go stale.")
    w("")
    w(f"Generated: {S.get('generated', 'unknown')}")
    w("")
    w("---")
    w("")

    # ---- 0. the instance ----------------------------------------------------
    inst = S.get("instance", {})
    if inst:
        sz = inst.get("size", {})
        w("## 0. The focal instance")
        w("")
        w(f"- JNPT (Nhava Sheva) corridor: {sz.get('nodes')} nodes, {sz.get('arcs')} arcs, "
          f"{sz.get('electrifiable')} electrifiable links, {sz.get('carriers')} carriers, "
          f"{sz.get('scenarios')} scenarios")
        w(f"- {inst.get('meta', {}).get('daily_boxes')} road containers per day, derived from "
          f"{m(inst.get('meta', {}).get('teu'))} TEU in {inst.get('meta', {}).get('teu_year')}")
        w(f"- Leader's design space: about 1e{math.log10(sz.get('design_space', 1)):.0f} "
          "distinct configurations")
        w(f"- Grid emission factors by scenario: {inst.get('ef')}")
        w(f"- Electricity prices by scenario (USD/kWh): {inst.get('price')}")
        md = inst.get("meta", {})
        if md.get("published_ef_avg") is not None:
            w(f"- **Calibration check.** The scenario tree's expected grid factor is "
              f"{md.get('expected_ef_kgco2_per_kwh')} against a published annual average of "
              f"{md.get('published_ef_avg')}, and its expected electricity price is "
              f"{md.get('expected_elec_price_usd_kwh')} against a published "
              f"{md.get('published_elec_price')}. The tree is constructed to match both "
              "exactly; if these disagree, every cross-country statement below is about the "
              "construction rather than about the country.")
            w(f"- Electric consumption: {md.get('e_battery_kwh_per_km')} kWh/km at the "
              f"battery, {md.get('charger_efficiency')} charging efficiency, so "
              f"{md.get('e_grid_kwh_per_km')} kWh/km drawn from the charger, which is the "
              "figure every emission and cost calculation uses.")
            w(f"- The charge a regulator would publish here: theta* = "
              f"{md.get('theta_star_usd_per_truck_km')} USD per truck-km on diesel "
              f"kilometres, sigma* = {md.get('sigma_star_usd_per_kwh')} USD/kWh by grid "
              f"state, which is {md.get('sigma_star_as_pct_of_elec_price')} per cent of the "
              "electricity price by state.")
        w("")

    # ---- 1. verification -----------------------------------------------------
    vs = read("validation_summary_jnpt.csv")
    if vs:
        w("## 1. Does the model compute what it claims to?")
        w("")
        w("| Test | What it checks | Result | Detail |")
        w("|---|---|---|---|")
        for r in vs:
            w(f"| {r['test']} | {r['description']} | **{r['result']}** | {r['detail']} |")
        w("")
        if all(r["result"] == "PASS" for r in vs):
            w("All six pass. The two that matter most are T2 and T3: two independently "
              "coded exact reformulations agree to solver tolerance, and on an instance "
              "small enough to enumerate, brute force over every electrification pattern "
              "returns the same optimum. Together they make a coding error in the "
              "reformulation very unlikely.")
        else:
            w("**At least one test fails. Nothing below should be trusted until it passes.**")
        w("")

    # ---- 2. instruments ------------------------------------------------------
    ins = read("instruments_jnpt.csv")
    if ins:
        fb = next((f(r["exp_social_cost_usd"]) for r in ins
                   if r["model"].startswith("centralized")), math.nan)
        gaps = {r["model"]: f(r["coordination_gap_usd"]) for r in ins
                if r["model"].startswith("F")}
        w("## 2. What is a corridor charge worth?")
        w("")
        w(f"First best (centralized): **{m(fb)} USD/yr**")
        w("")
        w("| Instrument family | Expected social cost | Coordination gap | Gap (%) |")
        w("|---|---|---|---|")
        for r in ins:
            if not r["model"].startswith("F"):
                continue
            w(f"| {r['model']} | {m(f(r['exp_social_cost_usd']))} | "
              f"{m(f(r['coordination_gap_usd']))} | {f(r['gap_pct']):.4f} |")
        w("")
        if gaps and max(gaps.values()) <= 1e-6 * max(1.0, abs(fb)):
            w("**Every family attains the first best, including the empty one.** At this "
              "carbon price the carriers' privately optimal operation already *is* the "
              "socially optimal operation, so there is nothing for a charge to correct. "
              "Read this as a result about the corridor, not about the instrument: where "
              "electricity is much cheaper than diesel and the grid is not catastrophically "
              "dirty, an authority that builds the right infrastructure does not need to "
              "price at all. It also means this table cannot discriminate between the "
              "families — sections 3 and 4 are where they separate.")
        else:
            worst = max(gaps, key=lambda k: gaps[k])
            w(f"The families separate. The worst is {worst}, leaving "
              f"{m(gaps[worst])} USD/yr on the table.")
        w("")

    # ---- 3. reach ------------------------------------------------------------
    rc = read("reach_jnpt.csv")
    if rc:
        base = f(rc[0]["min_attainable_emissions_kgco2"])
        w("## 3. Reach: the tightest emission target each instrument can induce")
        w("")
        w("| Instrument available | Least attainable CO2 (kg/yr) | Excess over the planner | Status |")
        w("|---|---|---|---|")
        for r in rc:
            e = f(r["min_attainable_emissions_kgco2"])
            w(f"| {r['family']} | {m(e)} | {100 * (e / base - 1):+.2f}% | {r['status']} |")
        w("")
        rv = {r["family"]: f(r["min_attainable_emissions_kgco2"]) for r in rc}
        if "F0" in rv and "F4" in rv and rv["F4"] < rv["F0"]:
            w(f"**This is where the instrument earns its keep.** With no corridor charge the "
              f"authority cannot induce annual emissions below **{m(rv['F0'])} kg**, however "
              f"it builds — that number is a certified optimum, so it is a proved bound. "
              f"With the state-contingent charge the same infrastructure reaches "
              f"**{m(rv['F4'])} kg**, which is "
              f"{100 * (rv['F0'] - rv['F4']) / rv['F0']:.1f}% lower and within "
              f"{100 * (rv['F4'] / base - 1):.1f}% of what a planner who could simply dictate "
              "operations would achieve. The priced figure comes from a solution the model "
              "exhibits, so it is attainable whether or not the search finished proving it "
              "minimal; a longer search can only move it down.")
            w("")
            w("Every emission target between those two numbers is reachable with the charge "
              "and reachable with no amount of infrastructure without it. Pricing is "
              "therefore not a refinement of a corridor decarbonisation programme; it is a "
              "precondition for the tighter half of it.")
        w("")

    # ---- 4. state contingency -------------------------------------------------
    ct = read("state_contingency_jnpt.csv")
    if ct:
        w("## 4. When does indexing the charge to the grid state pay?")
        w("")
        w("| Carbon price (USD/kg) | Grid-state spread | Gap, state-blind (F3) | Gap, state-contingent (F4) |")
        w("|---|---|---|---|")
        for r in ct:
            w(f"| {f(r['social_cost_of_carbon']):.2f} | {f(r['grid_state_spread']):.1f} | "
              f"{m(f(r['gap_F3']))} | {m(f(r['gap_F4']))} |")
        w("")
        bites = [r for r in ct if f(r["gap_F3"], 0) > 1e-3 and f(r["gap_F4"], 0) <= 1e-3]
        if bites:
            b = bites[0]
            w(f"The two coincide until the states are far enough apart and carbon expensive "
              f"enough. The first row where a state-blind charge leaves a gap and a "
              f"state-contingent one does not is a carbon price of "
              f"{1000 * f(b['social_cost_of_carbon']):,.0f} USD/t at a spread of "
              f"{f(b['grid_state_spread']):g}.")
        else:
            w("Across the whole grid tested, a single charge level always falls in the region "
              "that induces the socially optimal response in every scenario, so the extra "
              "instrument is never needed here. Theorem 2 guarantees the state-contingent "
              "charge always suffices; this says the state-blind one happens to as well on "
              "this instance, which is a statement about the instance and not the theory.")
        w("")

    # ---- 5. stochastic --------------------------------------------------------
    st = S.get("stochastic", {})
    ws = read("wait_and_see_jnpt.csv")
    if st:
        w("## 5. Is the uncertainty worth modelling?")
        w("")
        w(f"- WS (wait and see): {m(st['WS'])}")
        w(f"- RP (stochastic here-and-now): {m(st['RP'])}")
        w(f"- EEV (mean-value plan evaluated on the tree): {m(st['EEV'])}")
        w(f"- **VSS = {m(st['VSS'])}** ({100 * st['VSS'] / st['RP']:.2f}% of RP)")
        w(f"- **EVPI = {m(st['EVPI'])}** ({100 * st['EVPI'] / st['RP']:.2f}% of RP)")
        w("")
        if abs(st["VSS"]) <= 1e-6 * abs(st["RP"]):
            w("VSS is **zero**: the plan that is optimal for the mean scenario is also "
              "optimal against the full tree. EVPI is not. The distinction is easy to lose "
              "and worth keeping: what is worth nothing here is *modelling* the uncertainty, "
              "and what is worth something is *resolving* it.")
        if ws:
            cl = [int(f(r["n_electrified"])) for r in ws if "CL" in r["scenario"]]
            mg = [int(f(r["n_electrified"])) for r in ws if "MA" in r["scenario"]]
            if cl and mg and max(cl) != min(mg):
                w("")
                w(f"What sits behind EVPI is more informative than its size. Under perfect "
                  f"foresight the authority electrifies {max(cl)} links in every clean-grid "
                  f"scenario and {min(mg)} in every marginal-grid one: knowing which grid you "
                  "will charge from reverses the infrastructure decision outright. The "
                  "expensive uncertainty here is about the *grid*, not about demand, which is "
                  "unusual in corridor planning and says where an authority should spend its "
                  "forecasting effort.")
        w("")

    # ---- 6. collaboration -----------------------------------------------------
    sh = read("shapley_jnpt.csv")
    co = S.get("collaboration", {})
    cs = S.get("collab_seeds", {})
    if sh and co:
        w("## 6. Horizontal collaboration among the carriers")
        w("")
        w(f"- Stand-alone total: {m(co['standalone_total'])} USD/yr")
        w(f"- Grand coalition: {m(co['grand'])} USD/yr")
        w(f"- **Gain: {m(co['gain'])} USD/yr ({co['gain_pct']:.2f}%)**")
        d = co.get("decomposition", {})
        if d:
            tot = d.get("total_gain") or 1.0
            w(f"- Of which, with platooning switched off: {m(d.get('pooling_gain'))} "
              f"({100 * d.get('pooling_gain', 0) / tot:.0f}%), the rest being platooning and "
              "its interaction with pooling")
        w(f"- Shapley allocation in the core: {co.get('shapley_in_core')}; "
          f"least-core value {m(co.get('least_core_eps'))} "
          f"(non-empty core: {co.get('core_nonempty')})")
        w("")
        w("| Carrier | Stand-alone | Shapley | Saving | Saving (%) |")
        w("|---|---|---|---|---|")
        for r in sh:
            if r["carrier"] == "TOTAL":
                continue
            w(f"| {r['carrier']} | {m(f(r['standalone_cost']))} | {m(f(r['shapley_cost']))} | "
              f"{m(f(r['saving']))} | {f(r['saving_pct']):.2f} |")
        w("")
        if cs:
            w(f"Over ten independent draws of the carrier split the gain averages "
              f"{cs['mean_gain_pct']:.2f}% with a standard deviation of "
              f"{cs['sd_gain_pct']:.2f}% (range {cs['min_gain_pct']:.2f}–"
              f"{cs['max_gain_pct']:.2f}%), and the core is non-empty on "
              f"{'every' if cs.get('core_always_nonempty') else 'not every'} draw. The size "
              "of this gain is as much a property of how different the carriers are as a "
              "finding about collaboration, which is why it is reported as a distribution.")
        w("")

    # ---- 7. the threshold ------------------------------------------------------
    rt = read("reversal_thresholds.csv")
    if rt:
        e_lo = f(rt[0]["ef_neutral_low"])
        e_hi = f(rt[0]["ef_neutral_high"])
        e_mid = f(rt[0]["ef_neutral"])
        w("## 7. Does electrification cut CO2? It depends which emission factor you use")
        w("")
        w(f"Emission-neutral grid intensity, "
          f"`ef0 = f_diesel * ef_diesel / e_elec` = **{e_mid:.3f} kg CO2/kWh** centrally, "
          f"**{e_lo:.3f}–{e_hi:.3f}** over the published ranges of the two vehicle "
          "parameters. This number depends only on the two drivetrains — not on prices, not "
          "on policy, not on the corridor.")
        w("")
        w("| Country | State | Grid factor | Electric kg/km | Diesel kg/km | Verdict |")
        w("|---|---|---|---|---|---|")
        seen = set()
        for r in rt:
            k = (r["country"], r["scenario"])
            if k in seen:
                continue
            seen.add(k)
            w(f"| {r['country']} | {r['scenario']} | {f(r['ef_grid_kgco2_kwh']):.3f} | "
              f"{f(r['elec_kgco2_per_km']):.3f} | {f(r['diesel_kgco2_per_km']):.3f} | "
              f"{r['robustness_of_sign']} |")
        w("")
        efa, efm = reg["India"]["ef_avg"], reg["India"]["ef_marginal"]
        w(f"India is the interesting case, and the interest is not geographical. The Central "
          f"Electricity Authority publishes, in one edition of one database, an operating "
          f"margin of {efm} and a weighted average of {efa}. The operating margin sits above "
          f"the whole threshold interval, so against it electrification raises CO2 for every "
          f"admissible vehicle pair. The weighted average sits *inside* the interval, so "
          f"against it the sign is not determined by the published data at all. Which factor "
          "a policy analysis picks decides the answer, and no number of additional case "
          "studies settles it.")
        w("")
        flips = [f(r["carbon_price_flip_usd_kg"]) for r in rt
                 if r["carbon_price_flip_usd_kg"]]
        if flips:
            w(f"The *social* ranking is a separate question. Electrification still lowers "
              f"weighted social cost against India's operating margin at the central carbon "
              f"price; the price at which that reverses is about "
              f"{1000 * min(flips):,.0f} USD/t, which is inside the range the US EPA itself "
              "publishes. So this is a live policy question rather than a curiosity.")
        w("")

    # ---- 8. cross country -------------------------------------------------------
    cc = read("cross_country.csv")
    if cc:
        w("## 8. Eight corridors, eight grids")
        w("")
        w("| Port | Country | First best | No charge | F4 | Links electrified | Emission cut (%) |")
        w("|---|---|---|---|---|---|---|")
        for r in cc:
            w(f"| {r['port']} | {r['country']} | {m(f(r['cost_first_best']))} | "
              f"{m(f(r['cost_no_charge']))} | {m(f(r['cost_F4']))} | "
              f"{r['n_elec_F4']}/{r['n_edges']} | {f(r['emission_cut_pct']):.2f} |")
        w("")

    rm = read("regime_matrix.csv")
    if rm:
        nets = sorted({r["network"] for r in rm})
        regs = sorted({r["regime_country"] for r in rm})
        w("Electric share of truck movements, corridor (row) by energy regime (column):")
        w("")
        w("| corridor | " + " | ".join(regs) + " |")
        w("|" + "---|" * (len(regs) + 1))
        spread_row, spread_col = [], []
        for n in nets:
            vals = []
            for c in regs:
                v = next((f(r["pct_truck_movements_electric"]) for r in rm
                          if r["network"] == n and r["regime_country"] == c), math.nan)
                vals.append(v)
            spread_row.append(max(vals) - min(vals))
            w(f"| {n} | " + " | ".join(f"{v:.0f}%" for v in vals) + " |")
        for c in regs:
            vals = [f(r["pct_truck_movements_electric"]) for r in rm
                    if r["regime_country"] == c]
            spread_col.append(max(vals) - min(vals))
        w("")
        w(f"Average spread across a row (same corridor, different grids): "
          f"{sum(spread_row) / len(spread_row):.0f} percentage points. "
          f"Average spread down a column (same grid, different corridors): "
          f"{sum(spread_col) / len(spread_col):.0f} points. "
          + ("The energy regime dominates the topology, which is the precise sense in which "
             "a single-country study does and does not generalise."
             if sum(spread_row) / len(spread_row) > sum(spread_col) / len(spread_col)
             else "The topology dominates the energy regime here, which is the opposite of "
                  "what we expected and is discussed in the paper."))
        w("")

    # ---- 9. scalability ----------------------------------------------------------
    sc = read("scalability.csv")
    if sc:
        w("## 9. Does the exact method scale?")
        w("")
        w("| Instance | links | carriers | scenarios | log10 design space | "
          "SD binaries | SD time (s) | KKT binaries | KKT time (s) | enum time (s) |")
        w("|---|---|---|---|---|---|---|---|---|---|")
        for r in sc:
            w(f"| {r['instance']} | {r['n_edges']} | {r['n_carriers']} | {r['n_scenarios']} | "
              f"{f(r['log10_design_space']):.1f} | {r['sd_binaries']} | "
              f"{f(r['sd_runtime_s']):.1f} | {r['kkt_binaries']} | "
              f"{f(r['kkt_runtime_s']):.1f} | {r['enum_runtime_s'] or '-'} |")
        w("")
        rat = [f(r["kkt_binaries"]) / f(r["sd_binaries"]) for r in sc
               if r["sd_binaries"] and r["kkt_binaries"] and f(r["sd_binaries"]) > 0]
        if rat:
            w(f"The KKT model carries between {min(rat):.0f} and {max(rat):.0f} times as many "
              "binary variables, and the ratio grows with the *followers'* problem — with "
              "carriers, nodes and scenarios — none of which the leader chooses. That is why "
              "the gap widens rather than staying proportional.")
        w("")

    # ---- 10. caveats --------------------------------------------------------------
    w("## 10. What not to conclude")
    w("")
    w("- The instance is **calibrated, not measured**. Throughput, prices, emission factors "
      "and vehicle technology are published figures; the split of a corridor's volume across "
      "nodes and carriers is a documented, seeded rule. See `data/DATA_SOURCES.md`, which is "
      "explicit about which is which.")
    w("- Energy is accounted **per arc**. A battery-electric truck's state of charge along a "
      "path is not tracked, so the model gives an optimistic view of how little charging "
      "capacity suffices.")
    w("- The grid state is a **scenario, not an hour**. The charging-window question — when "
      "in the day to draw the energy — is one this model frames but does not answer.")
    w(f"- The emission threshold is a statement about a 40 t tractor-semitrailer drawing "
      f"{pars['e_elec']['value'] / pars['charger_efficiency']['value']:.2f} kWh per km from "
      "the charger, not about electric trucks in general. The interval around it is wide "
      "because that figure is not well measured at 40 t, **not** because the grids are "
      "poorly measured. If one number in this package deserves a better source, it is this "
      "one.")
    w("- The outer grid states for every country except India are **constructed**, "
      "and their clean states are below anything those majority-fossil systems reach today. "
      "The *mean* of each country's tree is calibrated to its published annual average, so "
      "no aggregate result depends on the outer levels; but the state *spread*, which is "
      "what makes state-contingent pricing worth anything, is a construction for three of "
      "the eight countries.")
    w("- The regime matrix separates carbon from topology only in its **grid-only** panel. "
      "The full-regime panel also moves both fuel prices and the non-fuel haulage cost, "
      "which ranges threefold across these eight countries and is not a property of any "
      "power system.")
    w("- The corridor networks are comparable as modelling objects of similar structure, "
      "**not** as equally complete representations of their hinterlands. Rotterdam's and "
      "Manzanillo's absorb their ports' whole hinterland road volume onto a handful of "
      "nodes, so their arc volumes are high relative to reality.")
    w("- **Reach** is an optimistic measure: where the coalition is indifferent between "
      "optima the leader is assumed to get the one it prefers. The comparison between "
      "families is unaffected; the absolute levels are optimistic.")
    w("- The exact method is **not** needed for the recommended instrument. Theorem 2 makes "
      "the followers' objective identical to the social one, so that case is a single-level "
      "MILP. What needed exactness is everything about the *restricted* instruments.")
    w("- Where a result is an incumbent rather than a certified optimum, the `status` and "
      "`certified_mip_gap` columns of the result files say so. Attainability claims cite an "
      "exhibited solution and impossibility claims cite a proved bound; neither cites the "
      "other.")
    w("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
